services:
  scrix:
    image: scrix/scrix:latest
    container_name: scrix
    build: .
    volumes:
      - scrix-config:/config
    environment:
      - SCRIX_LOG_LEVEL=info
    restart: unless-stopped
    network_mode: host

volumes:
  scrix-config:
